# Site Info
title: "Welcome to the randoms..."
tagline: 'Systems engineer. Robotics geek. Maker of shiny things. Part race car, part glitter.</br> Powered by caffeine and curiosity.'
description: 'A Jekyll theme adapted from <a href="http://lanyon.getpoole.com/" target="_blank">Lanyon</a>.'
#baseurl: "/"
#url: http://www.dxrf.com
logo: '/public/logo.png'

# Site configurations
plugins:
  - jekyll-paginate
  - jekyll-feed
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 2.0.0
exclude: [vendor]

# About/contact
author:
  name: Jenna Massardo
  description: Systems engineer. Robotics geek. Maker of shiny things. Part race car, part glitter. Powered by caffeine and curiosity.
  gravatar: 69ea17ec24451281f083ff214479fb07 # md5 hash of your email address
  contact:
    linkedin:  https://www.linkedin.com/in/jenna-massardo/
    github:    https://github.com/jmassardo
    facebook:  https://www.facebook.com/jennamassardo
    threads:   https://www.threads.net/@jennamassardo
    instagram: https://www.instagram.com/jennamassardo/
    #weibo:     http://weibo.com/41173780
    email:     mailto:jenna@dxrf.com

# Navigation (2nd level links supported)
nav:
  Home:
    - '/'
  Blog:
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  Resume:
    - '/resume/'
  Projects:
    - '/projects/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: https://imgs.xkcd.com/comics/circuit_diagram.png
  imageurl: https://xkcd.com/730/
  caption: Welcome to my world! <br><small> Thanks <a href="https://xkcd.com/">XKCD</a> for another awesome comic</small>

# Plugins
mathjax: true # whether support mathjax
google_analytics_token: 'G-R8J4XTV6XW' # leave blank if you don't want google analytics
#disqus_short_name: '' # leave blank if you don't want disqus
